/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parkingClass;

public class ParkingLot{
	
	//variable names
	private String parkingReserved;
    private String parkingUnreserved;
    private String parkingVehicleNo;
    private String parkingId;
	public ParkingLot(String parkingReserved, String parkingUnreserved, String parkingVehicleNo, String parkingId) {
		super();
		this.parkingReserved = parkingReserved;
		this.parkingUnreserved = parkingUnreserved;
		this.parkingVehicleNo = parkingVehicleNo;
		this.parkingId = parkingId;
	}
	public String getParkingReserved() {
		return parkingReserved;
	}
	public void setParkingReserved(String parkingReserved) {
		this.parkingReserved = parkingReserved;
	}
	public String getParkingUnreserved() {
		return parkingUnreserved;
	}
	public void setParkingUnreserved(String parkingUnreserved) {
		this.parkingUnreserved = parkingUnreserved;
	}
	public String getParkingVehicleNo() {
		return parkingVehicleNo;
	}
	public void setParkingVehicleNo(String parkingVehicleNo) {
		this.parkingVehicleNo = parkingVehicleNo;
	}
	public String getParkingId() {
		return parkingId;
	}
	public void setParkingId(String parkingId) {
		this.parkingId = parkingId;
	}
}
